version: '3'

services:
  strapi:
    build: .
    image: strapi-app
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    ports:
      - '1337:1337'
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./package.json:/opt/app/package.json
      - ./package-lock.json:/opt/app/package-lock.json
      - ./.env:/opt/app/.env
      - strapi-data:/opt/app/.tmp
      - strapi-uploads:/opt/app/public/uploads
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres-data:
  strapi-data:
  strapi-uploads: 